### ISSUE TITLE
Mutation.ex won't compile in Elixir 1.3

### ISSUE THREAD

**Issue by thaterikperson** [seanabrahams/graphql-relay-elixir#25]
It appears Elixir 1.3 doesn't work with the anonymous function in [GraphQL.Relay.Mutation.new/1](https://github.com/graphql-elixir/graphql_relay/blob/947bd401a06111f4ab1f94188118e6fdf4842dc7/lib/graphql/relay/mutation.ex#L49).

```
== Compilation error on file web/router.ex ==
** (ArgumentError) cannot escape #Function<0.44923427/3 in GraphQL.Relay.Mutation.new/1>. The supported values are: lists, tuples, maps, atoms, numbers, bitstrings, pids and remote functions in the format &Mod.fun/arity
```

I confirmed this works in Elixir 1.2.4 and Phoenix 1.1.4.
### web/router.ex

``` elixir
#…
scope "/q" do
  forward "/", GraphQL.Plug, schema: {GraphQLTest.Root, :schema}
end
#…
```
### web/graphql/root.ex

``` elixir
defmodule GraphQLTest.Root do

  alias GraphQL.Relay.Mutation

  def schema do
    %GraphQL.Schema{
      query: %GraphQL.Type.ObjectType{
        name: "Query",
        fields: %{
          greeting: %{
            type: %GraphQL.Type.String{},
            resolve: &GraphQLTest.Root.greeting/3,
          },
        }
      },
      mutation: %GraphQL.Type.ObjectType{
        name: "Mutation",
        fields: %{
          addUser: Mutation.new(%{
            name: "addUser",
            input_fields: %{
              name: %{type: %GraphQL.Type.String{}},
            },
            output_fields: %{
              name: %{type: %GraphQL.Type.String{}},
            },
            mutate_and_get_payload: &GraphQLTest.Root.mutate_and_get_payload/2,
          })
        }
      }
    }
  end

  def mutate_and_get_payload(input, info), do: %{name: "Hello #{input["name"]}"}
  def greeting(_, _, _), do: %{name: "Hello world"}
end
```

---

I don't have any great ideas for a solution. My current workaround is to include most of the Mutation.ex code directly in my own file so I can avoid the anonymous function. I'm still a bit of an Elixir beginner so would love to learn a true Elixir way to fix this.

**Comment by seanabrahams** [comment]
Interesting. I'm running Elixir 1.3.0 and Phoenix 1.2.0 without issues.

Is the `web/graphql/root.ex` shown here the working version? I don't see any call to `GraphQL.Relay.Mutation.new/1`.

My router config looks a bit different:

``` elixir
  scope "/graphql" do
    pipe_through :api

    get "/", GraphQL.Plug.Endpoint,
      schema: {GraphQL.Schema.Root, :schema},
      root_value: {GraphQL.Schema.Root, :root_value}
    post "/", GraphQL.Plug.Endpoint,
      schema: {GraphQL.Schema.Root, :schema},
      root_value: {GraphQL.Schema.Root, :root_value}
  end
```

**Comment by thaterikperson** [comment]
That is the failing `root.ex`. The `Mutation.new` call is tucked in there.

``` elixir
mutation: %GraphQL.Type.ObjectType{
  fields: %{
    addUser: Mutation.new(%{
```

Thanks for adding your router config. Using `get` and `post` rather than `forward` make it work properly.

**Comment by seanabrahams** [comment]
Ah yes, thanks for pointing it out.

@joshprice the docs for `plug_graphql` use the `forward` function version shown above. We need to look into why this fails.

**Comment by seanabrahams** [comment]
Closing since the issue appears to be in `plug_graphql`. Anyone reading this in the future be sure to try the router config in my comment above: https://github.com/graphql-elixir/graphql_relay/issues/25#issuecomment-228562490
